#
###################################
# Site wide configuration
####################################
#
title: David Whipp
email:
description: David Whipp's personal website
url: davewhipp.github.io # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Helsinki
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: David Whipp
  avatar: Whipp-face-circle.png
  job: "Associate professor of Geodynamic Modelling"
  bio: "I like computers, rocks and, nature."
  email: david.whipp@helsinki.fi
  disqus-shortname:
  twitter: dave_whipp
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: davewhipp
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: dwhipp #username
  skype: dwhipp3980 #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: IvX6ZFgUP5DgvBSomhz-yw #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
